### PR TITLE
Require `libopencv *=headless*` in tests on Linux

### LINKED ISSUE #117: Recent builds are failing
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
FAILED tests/test_metadata.py::test_prepare_metadata[metadata2asset_3.json-metadata2] - requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ontobee.org', port=443): Max retries exceeded with url: /browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_1234175 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
FAILED tests/test_metadata.py::test_prepare_metadata[metadata2asset_cellline.json-metadata3] - requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ontobee.org', port=443): Max retries exceeded with url: /browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_1234175 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
FAILED tests/test_metadata.py::test_parseobourl[http://purl.obolibrary.org/obo/NCBITaxon_10090-value0] - requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ontobee.org', port=443): Max retries exceeded with url: /browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_10090 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
FAILED tests/test_metadata.py::test_parseobourl[http://purl.obolibrary.org/obo/NCBITaxon_10116-value1] - requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ontobee.org', port=443): Max retries exceeded with url: /browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_10116 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
FAILED tests/test_metadata.py::test_parseobourl[http://purl.obolibrary.org/obo/NCBITaxon_28584-value2] - requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ontobee.org', port=443): Max retries exceeded with url: /browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_28584 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
FAILED tests/test_metadata.py::test_species - requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ontobee.org', port=443): Max retries exceeded with url: /browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_28584 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
ERROR tests/test_organize.py::test_video_organize[symlink-copy] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize[symlink-move] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize[copy-copy] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize[copy-move] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize[move-copy] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize[move-move] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize[hardlink-copy] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize[hardlink-move] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize_common[copy-0] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
ERROR tests/test_organize.py::test_video_organize_common[move-1] - ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
= 6 failed, 428 passed, 273 skipped, 1 deselected, 1 xfailed, 26 warnings, 10 errors in 74.55s (0:01:14) =
WARNING: Tests failed for dandi-0.61.2-py311h38be061_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: dandi-0.61.2-py311h38be061_0.conda
```
obolibrary I think should be resolved now , but the other one I have only vague memory of seeing

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

### PR DESCRIPTION
**Pull request by jwodder**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #117.

### CODE REVIEW

**Comment by jwodder** [comment]
@conda-forge-admin Please rerender.

**Comment by jwodder** [comment]
@conda-forge-admin Please rerender.

**Comment by jwodder** [comment]
@conda-forge-admin Please rerender.

**Comment by jwodder** [comment]
@conda-forge-admin Please rerender.

**Comment by yarikoptic** [comment]
Thank you @jwodder !

**Pull request merged**
